//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazinProd.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id_order { get; set; }
        public Nullable<int> Id_telephones { get; set; }
        public Nullable<int> Id_users { get; set; }
    
        public virtual Telephones Telephones { get; set; }
        public virtual Users Users { get; set; }
    }
}
